name: "Azure Blob Upload Action"
author: "Brian Mullin <brian.mullin@karlsgate.com>"
description: "Uploads local files to Azure Blob Storage containers"
branding:
  icon: "box"
  color: "blue"
inputs:
  connection_string:
    description: "The connection string with SAS token for the destination storage account"
    required: true
  container_name:
    description: "The name of the destination storage account container"
    required: true
  source_directory:
    description: "The local directory containing the files to upload"
    required: true
  file_pattern:
    description: "An optional file pattern to limit the files uploaded from the source directory"
    required: false
  file_overwrite:
    description: "An optional boolean to overwrite existing files in the destination storage account"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
